package visualizacionwearables.vista;

import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;

/**
 * Clase VentanaPrincipalVista, representa la ventana principal del programa,
 * es la encargada de contener el resto de ventanas internas y la ventana
 * desde la cual podremos seleccionar los archivos a leer.
 * 
 * @author  Daniel González Alonso
 * @since   27/07/2016
 * @version 1.0
 */
public class VentanaPrincipalVista extends javax.swing.JFrame {

    private VentanaPrincipalControlador miControlador; /** El controlador de 
                                                        * la ventana actual */
    
    /** Constructor de VentanaPrincipalVista, crea la Ventana Principal
     * 
     * @param controlador el controlador que se encargara de validar los datos
     *          de la vista y actualizarla con los datos del modelo. */
    public VentanaPrincipalVista(VentanaPrincipalControlador controlador) {
        miControlador = controlador;
        initComponents();
    }
    
    /** @return el tamaño vertical disponible para las ventanas internas */
    public int getInternaleFramesPanelWidth() {
        return internalFramesPanel.getWidth();
    }
    
    /** @return el tamaño horizontal disponible para las ventanas internas */
    public int getInternaleFramesPanelHeight() {
        return internalFramesPanel.getHeight();
    }
    
    /** Añade una ventana interna a la ventana principal */
    public void addInternalFrame(JInternalFrame newInternalFrame) {
        internalFramesPanel.add(newInternalFrame);
    }
    
    /** @return las ventanas internas de la ventana */
    public JInternalFrame[] getInternalFrames() {
        return internalFramesPanel.getAllFrames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFramesPanel = new javax.swing.JDesktopPane();
        barraHerramientas = new javax.swing.JMenuBar();
        FileMenuButton = new javax.swing.JMenu();
        OpenFileMenuButton = new javax.swing.JMenuItem();
        ViewMenuButton = new javax.swing.JMenu();
        SplitHorizontalMenuButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        internalFramesPanel.setOpaque(false);

        javax.swing.GroupLayout internalFramesPanelLayout = new javax.swing.GroupLayout(internalFramesPanel);
        internalFramesPanel.setLayout(internalFramesPanelLayout);
        internalFramesPanelLayout.setHorizontalGroup(
            internalFramesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        internalFramesPanelLayout.setVerticalGroup(
            internalFramesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        FileMenuButton.setText("Archivo");

        OpenFileMenuButton.setText("Abrir...");
        OpenFileMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileMenuButtonActionPerformed(evt);
            }
        });
        FileMenuButton.add(OpenFileMenuButton);

        barraHerramientas.add(FileMenuButton);

        ViewMenuButton.setText("Vista");

        SplitHorizontalMenuButton.setText("Dividir Horizontalmente");
        SplitHorizontalMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SplitHorizontalMenuButtonActionPerformed(evt);
            }
        });
        ViewMenuButton.add(SplitHorizontalMenuButton);

        barraHerramientas.add(ViewMenuButton);

        setJMenuBar(barraHerramientas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFramesPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFramesPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileMenuButtonActionPerformed
        
        final JFileChooser fc = new JFileChooser();
        
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {;
            miControlador.onSelectedFile(fc.getSelectedFile());
        }
    }//GEN-LAST:event_OpenFileMenuButtonActionPerformed

    private void SplitHorizontalMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SplitHorizontalMenuButtonActionPerformed
        miControlador.onSplit();
    }//GEN-LAST:event_SplitHorizontalMenuButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenuButton;
    private javax.swing.JMenuItem OpenFileMenuButton;
    private javax.swing.JMenuItem SplitHorizontalMenuButton;
    private javax.swing.JMenu ViewMenuButton;
    private javax.swing.JMenuBar barraHerramientas;
    private javax.swing.JDesktopPane internalFramesPanel;
    // End of variables declaration//GEN-END:variables
}
